name: neoeats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  fl_chart: ^0.69.2
  flutter_launcher_icons: ^0.14.2
  font_awesome_flutter: ^10.8.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  sqflite_common_ffi: ^2.0.0
  sqflite: ^2.0.0
  ffi: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/image/
    - assets/image/logo.png
    - assets/icons/icon.png

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

  